// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsgw5mKuQ0GiYWjZeZrGebLiLX7q3D9xg',
    appId: '1:938690782201:web:bf886debca9896c2041328',
    messagingSenderId: '938690782201',
    projectId: 'portfolio-danilo-8a975',
    authDomain: 'portfolio-danilo-8a975.firebaseapp.com',
    storageBucket: 'portfolio-danilo-8a975.appspot.com',
    measurementId: 'G-15ZPMKXGVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNrNUQPbQoDYbRJCPLdLXtlKwA8KDR2c8',
    appId: '1:938690782201:android:1b4c84e18c4769cc041328',
    messagingSenderId: '938690782201',
    projectId: 'portfolio-danilo-8a975',
    storageBucket: 'portfolio-danilo-8a975.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI8M7sGspisffVVToJ_jDEZkECX2so9dA',
    appId: '1:938690782201:ios:26224f9b09a5407b041328',
    messagingSenderId: '938690782201',
    projectId: 'portfolio-danilo-8a975',
    storageBucket: 'portfolio-danilo-8a975.appspot.com',
    iosBundleId: 'br.dev.danilosouza.portfolioDanilo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI8M7sGspisffVVToJ_jDEZkECX2so9dA',
    appId: '1:938690782201:ios:eccee8e398884435041328',
    messagingSenderId: '938690782201',
    projectId: 'portfolio-danilo-8a975',
    storageBucket: 'portfolio-danilo-8a975.appspot.com',
    iosBundleId: 'br.dev.danilosouza.portfolioDanilo.RunnerTests',
  );
}
